http:
  host: "0.0.0.0"
  port: "8081"
  
aws:
  accesskey: "![PrCrBZZI6T4wJMoFV50lHzYB+X8Ed9ymGqcdjoyCK3U=]"
  secretkey: "![zMfqNu0yQHuy0e/Wbm0EAAyLZtF2MSjwZH87kzckM09s32ehituC3DiUL0o1X+BT]"
  regionendpoint: "us-east-1"
  s3:
    bucketname: "qubotica-po-process"
  putobject:
    bucketname: "backup-qubotica"
  sqs:
    arn: "arn:aws:sqs:us-east-1:484907510455:qubotica-po-sqs"
    url: "https://sqs.us-east-1.amazonaws.com/484907510455/qubotica-po-sqs"
onnewobject:
  schedulingstrategy: "Fixed frequency"
  frequency: "1" 
  startdelay: "0"
  timeunit: "MINUTES"    
functionalIdentifier: "qbotica-po"

generic:
  maxretries: "3"
  millisecondsbetweenretries: "30000"
  
reconnection:
  frequency: "3000" 
  reconnectionattempts: "3"

